services:
    #Postgress Database
    postgres:
        image: docker.io/postgres
        environment:
            - POSTGRES_PASSWORD=postgres_password
    #Redis Database        
    redis:
        image: docker.io/redis
        command: ["redis-server", "--protected-mode", "no"]
    #Express API server    
    api:
        build: ./server
        image: docker.io/vakhila/complex-api
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    #Worker service         
    worker:
        build: ./worker
        image: docker.io/vakhila/complex-worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379  
    #React client 
    client:
        build: ./client
        image: docker.io/vakhila/complex-client
    #Nginx controller
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            context: ./nginx
        ports:
            - '8050:80'       